# Application Constants
APP_NAME = "My Flask App"
DEBUG_MODE = True
HOST = '0.0.0.0'
PORT = 5000

# BMI Constants
BMI_UNDERWEIGHT = 18.5
BMI_NORMAL = 25
BMI_OVERWEIGHT = 30

# BMI Categories
BMI_CATEGORY_UNDERWEIGHT = "Underweight"
BMI_CATEGORY_NORMAL = "Normal weight"
BMI_CATEGORY_OVERWEIGHT = "Overweight"
BMI_CATEGORY_OBESE = "Obese"

# Gender Constants
GENDER_MALE = 'male'

# Calorie Calculation Constants
MALE_BMR_CONSTANT = 88.362
MALE_BMR_WEIGHT_FACTOR = 13.397
MALE_BMR_HEIGHT_FACTOR = 4.799
MALE_BMR_AGE_FACTOR = 5.677

FEMALE_BMR_CONSTANT = 447.593
FEMALE_BMR_WEIGHT_FACTOR = 9.247
FEMALE_BMR_HEIGHT_FACTOR = 3.098
FEMALE_BMR_AGE_FACTOR = 4.330

HEIGHT_CM_CONVERSION = 100

# Activity Level Factors
ACTIVITY_FACTOR_SEDENTARY = 1.2
ACTIVITY_FACTOR_LIGHTLY_ACTIVE = 1.375
ACTIVITY_FACTOR_MODERATELY_ACTIVE = 1.55
ACTIVITY_FACTOR_VERY_ACTIVE = 1.725
ACTIVITY_FACTOR_EXTRA_ACTIVE = 1.9

# Template Names
TEMPLATE_INDEX = 'index.html'
TEMPLATE_RESULT = 'result.html'